version: '3.8'
services:
  app:
    build:
      context: .
    container_name: app
    links:
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch
      - kibana
    restart: always
    environment: 
      - PORT=9000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elk
    ports:
      - 9000:9000
      
  kibana:
    container_name: kibana
    build:
       context: kibana/
       args:
         ELK_VERSION: 7.5.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    build:
        context: elasticsearch
        args:
          ELK_VERSION: 7.5.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/storage:/usr/share/elasticsearch/data:rw

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=*
    networks:
      - elk
    ulimits:
      memlock:
        soft:  -1
        hard:  -1

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  log-data:
    
